
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const ADMIN_USERS_FETCH_REQUEST = 'ADMIN_USERS_FETCH_REQUEST';
export const ADMIN_USERS_FETCH_SUCCESS = 'ADMIN_USERS_FETCH_SUCCESS';
export const ADMIN_USERS_FETCH_FAILURE = 'ADMIN_USERS_FETCH_FAILURE';

export const ADMIN_USER_BLOCK_REQUEST = "ADMIN_USER_BLOCK_REQUEST";
export const ADMIN_USER_BLOCK_SUCCESS = " ADMIN_USER_BLOCK_SUCCESS";
export const ADMIN_USER_BLOCK_FAILURE = "ADMIN_USER_BLOCK_FAILURE";

export const ADMIN_USER_DELETE_REQUEST = "ADMIN_USER_DELETE_REQUEST";
export const ADMIN_USER_DELETE_SUCCESS = "ADMIN_USER_DELETE_SUCCESS";
export const ADMIN_USER_DELETE_FAILURE = "ADMIN_USER_DELETE_FAILURE";

export const ADMIN_BOOK_ADD_REQUEST = "ADMIN_BOOK_ADD_REQUEST";
export const ADMIN_BOOK_ADD_SUCCESS = "ADMIN_BOOK_ADD_SUCCESS";
export const ADMIN_BOOK_ADD_FAILURE = "ADMIN_BOOK_ADD_FAILURE";

export const ADMIN_BOOK_FETCH_REQUEST = 'ADMIN_BOOK_FETCH_REQUEST'
export const ADMIN_BOOK_FETCH_SUCCESS = 'ADMIN_BOOK_FETCH_SUCCESS'
export const ADMIN_BOOK_FETCH_FAILURE = 'ADMIN_BOOK_FETCH_FAILURE'


export const ADMIN_BOOK_DELETE_REQUEST = 'ADMIN_BOOK_DELETE_REQUEST'
export const ADMIN_BOOK_DELETE_SUCCESS = 'ADMIN_BOOK_DELETE_SUCCESS'
export const ADMIN_BOOK_DELETE_FAILURE = 'ADMIN_BOOK_DELETE_FAILURE'

export const ADMIN_GET_LOCATION_REQUEST = 'ADMIN_GET_LOCATION_REQUEST'
export const ADMIN_GET_LOCATION_SUCCESS = 'ADMIN_GET_LOCATION_SUCCESS'
export const ADMIN_GET_LOCATION_FAILURE = 'ADMIN_GET_LOCATION_FAILURE'

export const ADMIN_SEARCH_REQUEST = 'ADMIN_SEARCH_REQUEST'
export const ADMIN_SEARCH_SUCCESS = 'ADMIN_SEARCH_SUCCESS'
export const ADMIN_SEARCH_FAILURE = 'ADMIN_SEARCH_FAILURE'

export const ADMIN_ADD_GENRE_REQUEST = 'ADMIN_ADD_GENRE_REQUEST'
export const ADMIN_ADD_GENRE_SUCCESS = 'ADMIN_ADD_GENRE_SUCCESS'
export const ADMIN_ADD_GENRE_FAILURE = 'ADMIN_ADD_GENRE_FAILURE'

export const ADMIN_GENRES_FETCH_REQUEST = 'ADMIN_GENRES_FETCH_REQUEST'
export const ADMIN_GENRES_FETCH_SUCCESS = 'ADMIN_GENRES_FETCH_SUCCESS'
export const ADMIN_GENRES_FETCH_FAILURE = 'ADMIN_GENRES_FETCH_FAILURE'

export const ADMIN_GENRES_DELETE_REQUEST = 'ADMIN_GENRE_DELETE_REQUEST'
export const ADMIN_GENRES_DELETE_SUCCESS = 'ADMIN_GENRE_DELETE_SUCCESS'
export const ADMIN_GENRES_DELETE_FAILURE = 'ADMIN_GENRE_DELETE_FAILURE'

export const ADMIN_GET_ALL_ORDERS_REQUEST = 'ADMIN_GET_ALL_ORDERS_REQUEST'
export const ADMIN_GET_ALL_ORDERS_SUCCESS = 'ADMIN_GET_ALL_ORDERS_SUCCESS'
export const ADMIN_GET_ALL_ORDERS_FAILURE = 'ADMIN_GET_ALL_ORDERS_FAILURE'

export const ADMIN_GET_ALL_RETURN_REQUEST = 'ADMIN_GET_ALL_RETURN_REQUEST'
export const ADMIN_GET_ALL_RETURN_SUCCESS = 'ADMIN_GET_ALL_RETURN_SUCCESS'
export const ADMIN_GET_ALL_RETURN_FAILURE = 'ADMIN_GET_ALL_RETURN_FAILURE'

export const ADMIN_ACCEPT_RETURN_REQUEST = 'ADMIN_ACCEPT_RETURN_REQUEST'
export const ADMIN_ACCEPT_RETURN_SUCCESS = 'ADMIN_ACCEPT_RETURN_SUCCESS'
export const ADMIN_ACCEPT_RETURN_FAILURE = 'ADMIN_ACCEPT_RETURN_FAILURE'


export const ADMIN_GET_SELL_BOOKS_REQUEST = 'ADMIN_GET_SELL_BOOKS_REQUEST'
export const ADMIN_GET_SELL_BOOKS_SUCCESS = 'ADMIN_GET_SELL_BOOKS_SUCCESS'
export const ADMIN_GET_SELL_BOOKS_FAILURE = 'ADMIN_GET_SELL_BOOKS_FAILURE'

export const ADMIN_GET_DASHBOARD_DETAILS_REQUEST = 'ADMIN_GET_DASHBOARD_DETAILS_REQUEST'
export const ADMIN_GET_DASHBOARD_DETAILS_SUCCESS = 'ADMIN_GET_DASHBOARD_DETAILS_SUCCESS'
export const ADMIN_GET_DASHBOARD_DETAILS_FAILURE = 'ADMIN_GET_DASHBOARD_DETAILS_FAILURE'

export const ADMIN_GET_SALES_REPORT_REQUEST = 'ADMIN_GET_SALES_REPORT_REQUEST'
export const ADMIN_GET_SALES_REPORT_SUCCESS = 'ADMIN_GET_SALES_REPORT_SUCCESS'
export const ADMIN_GET_SALES_REPORT_FAILURE = 'ADMIN_GET_SALES_REPORT_FAILURE'
