export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const UPLOAD_USER_IMAGE_REQUEST = 'UPLOAD_USER_IMAGE_REQUEST';
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS';
export const UPLOAD_USER_IMAGE_FAILURE = 'UPLOAD_USER_IMAGE_FAILURE';

export const USER_GET_BOOKS_REQUEST = 'USER_GET_BOOKS_REQUEST';
export const USER_GET_BOOKS_SUCCESS = 'USER_GET_BOOKS_SUCCESS';
export const USER_GET_BOOKS_FAILURE = 'USER_GET_BOOKS_FAILURE';

export const USER_GET_GENRE_BOOKS_REQUEST = 'USER_GET_GENRE_BOOKS_REQUEST'
export const USER_GET_GENRE_BOOKS_SUCCESS = 'USER_GET_GENRE_BOOKS_SUCCESS'
export const USER_GET_GENRE_BOOKS_FAILURE = 'USER_GET_GENRE_BOOKS_FAILURE'

export const USER_BOOK_SEARCH_REQUEST = 'USER_BOOK_SEARCH_REQUEST'
export const USER_BOOK_SEARCH_SUCCESS = 'USER_BOOK_SEARCH_SUCCESS'
export const USER_BOOK_SEARCH_FAILURE = 'USER_BOOK_SEARCH_FAILURE'

export const USER_GET_ORDERED_BOOKS_REQUEST = 'USER_GET_ORDERED_BOOKS'
export const USER_GET_ORDERED_BOOKS_SUCCESS = 'USER_GET_ORDERED_BOOKS_SUCCESS'
export const USER_GET_ORDERED_BOOKS_FAILURE = 'USER_GET_ORDERED_BOOKS_FAILURE'

export const USER_ORDER_RETURN_REQUEST = 'USER_ORDER_RETURN_REQUEST'
export const USER_ORDER_RETURN_SUCCESS = 'USER_ORDER_RETURN_SUCCESS'
export const USER_ORDER_RETURN_FAILURE = 'USER_ORDER_RETURN_FAILURE'

export const USER_GENRES_FETCH_REQUEST = 'USER_GENRES_FETCH_REQUEST'
export const USER_GENRES_FETCH_SUCCESS = 'USER_GENRES_FETCH_SUCCESS'
export const USER_GENRES_FETCH_FAILURE = 'USER_GENRES_FETCH_FAILURE'

export const USER_FETCH_ADDRESSES_REQUEST = 'USER_FETCH_ADDRESSES_REQUEST'
export const USER_FETCH_ADDRESSES_SUCCESS = 'USER_FETCH_ADDRESSES_SUCCESS'
export const USER_FETCH_ADDRESSES_FAILURE = 'USER_FETCH_ADDRESSES_FAILURE'

export const USER_ADD_ADDRESS_REQUEST = 'USER_ADD_ADDRESS_REQUEST'
export const USER_ADD_ADDRESS_SUCCESS = 'USER_ADD_ADDRESS_SUCCESS'
export const USER_ADD_ADDRESS_FAILURE = 'USER_ADD_ADDRESS_FAILURE'

export const USER_BOOK_SELL_REQUEST_SUCCESS = 'USER_BOOK_SELL_REQUEST_SUCCESS'

export const USER_GET_SELL_BOOKS_REQUEST = 'USER_GET_SELL_BOOKS_REQUEST'
export const USER_GET_SELL_BOOKS_SUCCESS = 'USER_GET_SELL_BOOKS_SUCCESS'
export const USER_GET_SELL_BOOKS_FAILURE = 'USER_GET_SELL_BOOKS_FAILURE'

export const USER_SEND_SELLED_BOOK_REQUEST = 'USER_SEND_SELLED_BOOK_REQUEST'
export const USER_SEND_SELLED_BOOK_SUCCESS = 'USER_SEND_SELLED_BOOK_SUCCESS'
export const USER_SEND_SELLED_BOOK_FAILURE = 'USER_SEND_SELLED_BOOK_FAILURE'

export const USER_GET_WALLET_REQUEST = 'USER_GET_WALLET_REQUEST'
export const USER_GET_WALLET_SUCCESS = 'USER_GET_WALLET_SUCCESS'
export const USER_GET_WALLET_FAILURE = 'USER_GET_WALLET_FAILURE'

export const USER_BOOK_ORDER_REQUEST = 'USER_BOOK_ORDER_REQUEST';
export const USER_BOOK_ORDER_SUCCESS = 'USER_BOOK_ORDER_SUCCESS';
export const USER_BOOK_ORDER_FAILURE = 'USER_BOOK_ORDER_FAILURE';
